class DataProfileManager {
	private static readonly DEFAULT_PROFILES: FakeDataProfile[] = [
		{
			name: 'Default Professional',
			data: {
				firstName: 'John',
				lastName: 'Doe',
				email: 'john.doe@example.com',
				workEmail: 'john.doe@company.com',
				phone: '08012345678',
				age: '30',
				company: 'Tech Solutions Inc',
				jobTitle: 'Software Developer',
				salary: '75000',
				username: 'johndoe123',
				password: 'SecurePass123!',
				street: '123 Main Street',
				apartment: 'Apt 4B',
				city: 'Lagos',
				zipCode: '100001',
				emergencyName: 'Jane Doe',
				emergencyPhone: '08087654321',
				website: 'https://johndoe.dev',
				linkedin: 'https://linkedin.com/in/johndoe',
				ccNumber: '4532 1234 5678 9012',
				ccName: 'John Doe',
				ccExpiry: '12/26',
				ccCvv: '123',
				bio: 'Experienced software developer with a passion for creating innovative solutions.',
				dateOfBirth: '1993-05-15',
				gender: 'male',
				country: 'Nigeria',
				state: 'Lagos',
			},
		},
		{
			name: 'Student Profile',
			data: {
				firstName: 'Sarah',
				lastName: 'Johnson',
				email: 'sarah.johnson@student.edu',
				workEmail: 'sarah.j@parttime.com',
				phone: '08087654321',
				age: '22',
				company: 'University Library',
				jobTitle: 'Student Assistant',
				salary: '25000',
				username: 'sarahj22',
				password: 'StudentLife2024!',
				street: '456 Campus Drive',
				apartment: 'Dorm 12B',
				city: 'Ibadan',
				zipCode: '200001',
				emergencyName: 'Mary Johnson',
				emergencyPhone: '08098765432',
				website: 'https://sarahjohnson.blog',
				linkedin: 'https://linkedin.com/in/sarahjohnson',
				ccNumber: '4111 1111 1111 1111',
				ccName: 'Sarah Johnson',
				ccExpiry: '08/27',
				ccCvv: '456',
				bio: 'Computer Science student passionate about web development and user experience design.',
				dateOfBirth: '2002-03-20',
				gender: 'female',
				country: 'Nigeria',
				state: 'Oyo',
			},
		},
		{
			name: 'Senior Executive',
			data: {
				firstName: 'Michael',
				lastName: 'Williams',
				email: 'michael.williams@executive.com',
				workEmail: 'm.williams@corporation.com',
				phone: '08011111111',
				age: '45',
				company: 'Global Enterprises Ltd',
				jobTitle: 'Chief Technology Officer',
				salary: '150000',
				username: 'mwilliams_exec',
				password: 'Executive2024#',
				street: '789 Executive Boulevard',
				apartment: 'Penthouse A',
				city: 'Abuja',
				zipCode: '900001',
				emergencyName: 'Jennifer Williams',
				emergencyPhone: '08022222222',
				website: 'https://michaelwilliams.pro',
				linkedin: 'https://linkedin.com/in/michaelwilliams-cto',
				ccNumber: '5555 5555 5555 4444',
				ccName: 'Michael Williams',
				ccExpiry: '03/28',
				ccCvv: '789',
				bio: 'Seasoned technology executive with 20+ years of experience leading digital transformation initiatives.',
				dateOfBirth: '1979-11-10',
				gender: 'male',
				country: 'Nigeria',
				state: 'FCT',
			},
		},
	];

	static getCurrentProfile(): FakeDataProfile {
		// For now, return default. Later we'll implement profile switching
		return this.DEFAULT_PROFILES[0];
	}

	static getAllProfiles(): FakeDataProfile[] {
		return this.DEFAULT_PROFILES;
	}
}
